<script src="../js/jquery-3.5.1.min.js"></script>
<script>
/* function sum(a, b, fn) {
	var c = a + b;
	fn(c);
}

sum(1, 2, function(r){
	console.log(r * r);
}); */


/* setTimeout(function() {
	console.log('콜백실행');
	console.log('Hi~');
	setTimeout(function(){
		console.log('Hi2~');
		setTimeout(function(){
			console.log('Hi3~');
		}, 0);
	}, 0);
}, 0); */


/****************** Promise *******************/
/* var users;
var lists;
var booldookList;
$.get('../json/user.json', function(r){
	users = r.users;
	$.get('../json/board.json', function(r2) {
		lists = r2.lists;
		booldookList = lists.filter(function(v){
			return v.writer === 'booldook';
		});
		console.log(booldookList);
	});
}); */

/* function sum(a, b) {
	return new Promise(function(resolve, reject){
		if(typeof a === 'number' && typeof b === 'number') resolve(a + b);
		else reject('전달된 인자는 숫자여야 합니다.')
	});
}

sum(10, 20).then(function(r){
	console.log(r);
}).catch(function(err){
	console.log(err);
}); */


/*************** 최초에 콜백이 있었다. *****************/
function sum(a, b, fn) {
	var c = a + b;
	fn(c);
}
function multi(a, fn) {
	var b = a * a;
	fn(b);
}
function print(a, fn) {
	var txt = a + ' 입니다.';
	fn(txt);
}
sum(10, 20, function(r) {
	multi(r + 30, function(r2) {
		print('결과는 '+r2, function(r3) {
			console.log(r3);
		});
	});
});

/*************** 콜백지옥을 해결하기 위해 Promise가 만들어졌다. *****************/
function sum2(a, b) {
	return new Promise(function(resolve, reject) {
		if(typeof a === 'number' && typeof b === 'number') {
			var c = a + b;
			resolve(c);
		}
		else {
			var err = '숫자만 연산할 수 있습니다.1';
			reject(err);
		}
	});
}
function multi2(a) {
	return new Promise(function(resolve, reject) {
		if(typeof a === 'number') {
			var b = a * a;
			resolve(b);
		}
		else {
			var err = '숫자만 연산할 수 있습니다.2';
			reject(err);
		}
	});
}
function print2(a) {
	return new Promise(function(resolve, reject) {
		var txt = a + ' 입니다.';
		resolve(txt);
	});
}

sum2(10, 20)
.then(function(r) {
	return multi2(r + 30);
})
.then(function(r2) {
	return print2('결과는 ' + r2);
})
.then(function(r3) {
	console.log(r3);
})
.catch(function(err) {
	console.log(err);
});


sum(1, 2, function(r) {
	sum(r, 3, function(r2) {
		sum(r2, 4, function(r3) {
			sum(r3, 5, function(r4) {
				sum(r4, 6, function(r5) {
					console.log(r5);
				})
			})
		})
	})
});

sum2(1, 2)
.then(function(r) {
	return sum2(r, 3);
})
.then(function(r) {
	return sum2(r, 4);
})
.then(function(r) {
	return sum2(r, 5);
})
.then(function(r) {
	return sum2(r, 6);
})
.then(function(r) {
	return sum2(r, 7);
})
.then(function(r) {
	return sum2(r, 8);
})
.then(function(r) {
	return sum2(r, 9);
})
.then(function(r) {
	return sum2(r, 10);
})
.then(function(r) {
	console.log(r);
})

/*************** Promise가 편해졌나? NO - async/await *****************/
async function init() {
	try {
		var r;
		r = await sum2(10, 20);
		r = await multi2(r + 30);
		r = await print2('결과는 ' + r);
		console.log(r);

		r = await sum2(1, 2);
		r = await sum2(r, 3);
		r = await sum2(r, 4);
		r = await sum2(r, 5);
		r = await sum2(r, 6);
		r = await sum2(r, 7);
		r = await sum2(r, 8);
		r = await sum2(r, 9);
		r = await sum2(r, 10);
		console.log(r);
	}
	catch(err) {
		console.log(err);
	}
}

init();
</script>